// Code generated by goctl. DO NOT EDIT!
// Source: agent.proto

package main

import (
	"flag"
	"fmt"

	"github.com/bytehello/gcc-zero/service/agent/cmd/rpc/agent"
	"github.com/bytehello/gcc-zero/service/agent/cmd/rpc/internal/config"
	"github.com/bytehello/gcc-zero/service/agent/cmd/rpc/internal/server"
	"github.com/bytehello/gcc-zero/service/agent/cmd/rpc/internal/svc"

	"github.com/tal-tech/go-zero/core/conf"
	"github.com/tal-tech/go-zero/zrpc"
	"google.golang.org/grpc"
)

var configFile = flag.String("f", "etc/agent.yaml", "the config file")

func main() {
	flag.Parse()

	var c config.Config
	conf.MustLoad(*configFile, &c)
	ctx := svc.NewServiceContext(c)
	srv := server.NewAgentClientServer(ctx)

	s := zrpc.MustNewServer(c.RpcServerConf, func(grpcServer *grpc.Server) {
		agent.RegisterAgentClientServer(grpcServer, srv)
	})
	defer s.Stop()

	fmt.Printf("Starting rpc server at %s...\n", c.ListenOn)
	s.Start()
}
