// Code generated by goctl. DO NOT EDIT!
// Source: agent.proto

package server

import (
	"context"

	"github.com/bytehello/gcc-zero/service/agent/cmd/rpc/agent"
	"github.com/bytehello/gcc-zero/service/agent/cmd/rpc/internal/logic"
	"github.com/bytehello/gcc-zero/service/agent/cmd/rpc/internal/svc"
)

type AgentClientServer struct {
	svcCtx *svc.ServiceContext
}

func NewAgentClientServer(svcCtx *svc.ServiceContext) *AgentClientServer {
	return &AgentClientServer{
		svcCtx: svcCtx,
	}
}

func (s *AgentClientServer) ReleaseKv(ctx context.Context, in *agent.ReleaseKvReq) (*agent.ReleaseKvReply, error) {
	l := logic.NewReleaseKvLogic(ctx, s.svcCtx)
	return l.ReleaseKv(in)
}

func (s *AgentClientServer) ReleaseKvStat(ctx context.Context, in *agent.ReleaseKvStatReq) (*agent.ReleaseKvStatReply, error) {
	l := logic.NewReleaseKvStatLogic(ctx, s.svcCtx)
	return l.ReleaseKvStat(in)
}
