// Code generated by goctl. DO NOT EDIT.
package types

type AppAddReq struct {
	AppName string `json:"appName"`
	AppKey  string `json:"appKey"`
	Desc    string `json:"desc"`
}

type AppAddReply struct {
	Code    string `json:"code"`
	Id      int64  `json:"id"`
	Message string `json:"message"`
}

type AppListReq struct {
	Current  int64 `json:"current"`
	PageSize int64 `json:"pageSize,default=5"`
}

type ListAppData struct {
	Id      int64  `json:"id"`
	AppName string `json:"appName"`
	AppKey  string `json:"appKey"`
	Desc    string `json:"desc"`
}

type AppListReply struct {
	Code     string         `json:"code"`
	Message  string         `json:"message"`
	Data     []*ListAppData `json:"data"`
	Current  int64          `json:"current"`
	PageSize int64          `json:"pageSize"`
	Total    int64          `json:"total"`
}

type AppUpdateReq struct {
	Id      int64  `json:"id"`
	AppName string `json:"appName"`
	AppKey  string `json:"appKey"`
	Desc    string `json:"desc"`
}

type AppUpdateReply struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

type AppDelReq struct {
	Id int64 `json:"id"`
}

type AppDelReply struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

type ClusterAddReq struct {
	AppId       int64  `json:"appId"`
	ClusterName string `json:"clusterName"`
	Desc        string `json:"desc"`
}

type ClusterAddReply struct {
	Code    string `json:"code"`
	Id      int64  `json:"id"`
	Message string `json:"message"`
}

type ClusterDelReq struct {
	Id int64 `json:"id"`
}

type ClusterDelReply struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

type ClusterUpdateReq struct {
	Id          int64  `json:"id"`
	ClusterName string `json:"clusterName"`
	Desc        string `json:"desc"`
}

type ClusterUpdateReply struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

type ClusterListReq struct {
	Current  int64 `json:"current"`
	PageSize int64 `json:"pageSize"`
}

type ClusterListData struct {
	Id          int64  `json:"id"`
	AppId       int64  `json:"appId"`
	ClusterName string `json:"clusterName"`
	Desc        string `json:"desc"`
}

type ClusterListReply struct {
	Code     string             `json:"code"`
	Message  string             `json:"message"`
	Data     []*ClusterListData `json:"data"`
	Current  int64              `json:"current"`
	PageSize int64              `json:"pageSize"`
	Total    int64              `json:"total"`
}

type KvAddReq struct {
	AppId     int64  `json:"appId"`
	ClusterId int64  `json:"clusterId"`
	Key       string `json:"key"`
	Value     string `json:"value"`
	Desc      string `json:"desc"`
}

type KvAddReply struct {
	Code           string `json:"code"`
	Id             int64  `json:"id"`
	Version        int64  `json:"version"`
	CreateRevision int64  `json:"createRevision"`
	ModRevision    int64  `json:"modRevision"`
	Message        string `json:"message"`
}

type KvData struct {
	Id             int64  `json:"id"`
	AppId          int64  `json:"appId"`
	ClusterId      int64  `json:"clusterId"`
	Key            string `json:"key"`
	Value          string `json:"value"`
	Desc           string `json:"desc"`
	Version        int64  `json:"version"`
	PushStatus     int    `json:"pushStatus"`
	Format         string `json:"format"`
	CreateRevision int64  `json:"createRevision"`
	ModRevision    int64  `json:"modRevision"`
	CreateTime     string `json:"createTime"`
	UpdateTime     string `json:"updateTime"`
	PushedTime     string `json:"pushedTime"`
}

type KvGetReq struct {
	Id int64 `json:"id"`
}

type KvGetReply struct {
	Code    string `json:"code"`
	Message string `json:"message"`
	Data    KvData `json:"data"`
}

type KvUpdateReq struct {
	Id    int64  `json:"id"`
	Key   string `json:"key"`
	Value string `json:"value"`
	Desc  string `json:"desc"`
}

type KvUpdateReply struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

type KvDelReq struct {
	Id int64 `json:"id"`
}

type KvDelReply struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

type KvListReq struct {
	AppId     int64 `json:"appId"`
	ClusterId int64 `json:"clusterId"`
	PageSize  int64 `json:"pageSize"`
	Current   int64 `json:"current"`
}

type KvListReply struct {
	Code     string    `json:"code"`
	Message  string    `json:"message"`
	Total    int64     `json:"total"`
	PageSize int64     `json:"pageSize"`
	Current  int64     `json:"current"`
	List     []*KvData `json:"list"`
}

type KvReleaseReq struct {
	Id int64 `json:"id"`
}

type KvReleaseReply struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

type KvClientListReq struct {
	KvId int64 `json:"kvId"`
}

type KvClientData struct {
	Ip          string `json:"ip"`
	VisitedTime string `json:"visitedTime"`
	CreateTime  string `json:"createTime"`
	UpdateTime  string `json:"updateTime"`
	ReleaseTime string `json:"releaseTime"`
	KvId        int64  `json:"kvId"`
	AppId       int64  `json:"appId"`
	ClusterId   int64  `json:"clusterId"`
}

type KvClientListReply struct {
	Code    string          `json:"code"`
	Message string          `json:"message"`
	List    []*KvClientData `json:"list"`
}

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginReply struct {
	Code         string `json:"code"`
	Msg          string `json:"msg"`
	Id           int64  `json:"id"`
	Username     string `json:"username"`
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
}
