// Code generated by goctl. DO NOT EDIT!
// Source: cc.proto

package server

import (
	"context"

	"github.com/bytehello/gcc-zero/service/cc/cmd/rpc/cc"
	"github.com/bytehello/gcc-zero/service/cc/cmd/rpc/internal/logic"
	"github.com/bytehello/gcc-zero/service/cc/cmd/rpc/internal/svc"
)

type CcServer struct {
	svcCtx *svc.ServiceContext
}

func NewCcServer(svcCtx *svc.ServiceContext) *CcServer {
	return &CcServer{
		svcCtx: svcCtx,
	}
}

func (s *CcServer) AppAdd(ctx context.Context, in *cc.AppAddReq) (*cc.AppAddReply, error) {
	l := logic.NewAppAddLogic(ctx, s.svcCtx)
	return l.AppAdd(in)
}

func (s *CcServer) AppList(ctx context.Context, in *cc.AppListReq) (*cc.AppListReply, error) {
	l := logic.NewAppListLogic(ctx, s.svcCtx)
	return l.AppList(in)
}

func (s *CcServer) AppUpdate(ctx context.Context, in *cc.AppUpdateReq) (*cc.AppUpdateReply, error) {
	l := logic.NewAppUpdateLogic(ctx, s.svcCtx)
	return l.AppUpdate(in)
}

func (s *CcServer) AppDel(ctx context.Context, in *cc.AppDelReq) (*cc.AppDelReply, error) {
	l := logic.NewAppDelLogic(ctx, s.svcCtx)
	return l.AppDel(in)
}
