// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	sysuser "github.com/bytehello/gcc-zero/service/admin/cmd/api/internal/handler/sys/user"
	"github.com/bytehello/gcc-zero/service/admin/cmd/api/internal/svc"

	"github.com/tal-tech/go-zero/rest"
)

func RegisterHandlers(engine *rest.Server, serverCtx *svc.ServiceContext) {
	engine.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/sys/user/login",
				Handler: sysuser.LoginHandler(serverCtx),
			},
		},
	)
}
