// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	ccapp "github.com/bytehello/gcc-zero/service/admin/cmd/api/internal/handler/cc/app"
	cccluster "github.com/bytehello/gcc-zero/service/admin/cmd/api/internal/handler/cc/cluster"
	cckv "github.com/bytehello/gcc-zero/service/admin/cmd/api/internal/handler/cc/kv"
	sysuser "github.com/bytehello/gcc-zero/service/admin/cmd/api/internal/handler/sys/user"
	"github.com/bytehello/gcc-zero/service/admin/cmd/api/internal/svc"

	"github.com/tal-tech/go-zero/rest"
)

func RegisterHandlers(engine *rest.Server, serverCtx *svc.ServiceContext) {
	engine.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/cc/app/add",
				Handler: ccapp.AppAddHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/cc/app/list",
				Handler: ccapp.AppListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/cc/app/update",
				Handler: ccapp.AppUpdateHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/cc/app/del",
				Handler: ccapp.AppDelHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)

	engine.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/cc/cluster/add",
				Handler: cccluster.ClusterAddHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/cc/cluster/del",
				Handler: cccluster.ClusterDelHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/cc/cluster/update",
				Handler: cccluster.ClusterUpdateHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/cc/cluster/list",
				Handler: cccluster.ClusterListHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)

	engine.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/cc/kv/add",
				Handler: cckv.KvAddHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)

	engine.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/sys/user/login",
				Handler: sysuser.LoginHandler(serverCtx),
			},
		},
	)
}
